apiVersion: v1
kind: ReplicationController
metadata:
  name: es
  labels:
    component: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      serviceAccount: elasticsearch
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
containers:
  - name: es
    securityContext:
      capabilities:
        add:
          - IPC_LOCK
    image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.2
    env:
      - name: KUBERNETES_CA_CERTIFICATE_FILE
        value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt