apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"] # Sensitive
# TODO
